version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - '3001:3000'
    environment:
      - LOCAL_DB_URI=mongodb://mongo:27017/workshop1
    networks:
      - default

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=workshop1
    ports:
      - '27017:27017'
    networks:
      - default

networks:
  default:
    name: workshop1-backend
    driver: bridge
      