services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    environment:
      LOCAL_DB_URI: 'mongodb://mongo/workshop1'
      PORT: 4000
      FRONT_URL_DEV: 'http://localhost:3000'
      WOOCOMMERCE_URL: ${WOOCOMMERCE_URL}
      WOOCOMMERCE_USER_KEY: ${WOOCOMMERCE_USER_KEY}
      WOOCOMMERCE_SECRET_KEY: ${WOOCOMMERCE_SECRET_KEY}
    depends_on:
      - mongo
    ports:
      - '4000:4000'
    volumes:
      - ${PWD}/src:/usr/src/app/src
    networks:
      - back
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/mongodb:/data/db
    networks:
      - back
    restart: always

networks:
  back:
    name: 'back'
