services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    environment:
      - LOCAL_DB_URI=${LOCAL_DB_URI}
      - PORT=${PORT}
      - FRONT_URL_PROD=${FRONT_URL_PROD}
      - FRONT_URL_DEV=${FRONT_URL_DEV}
      - WOOCOMMERCE_URL=${WOOCOMMERCE_URL}
      - WOOCOMMERCE_USER_KEY=${WOOCOMMERCE_USER_KEY}
      - WOOCOMMERCE_SECRET_KEY=${WOOCOMMERCE_SECRET_KEY}
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}/src:/usr/src/app/src
    networks:
      - workshop1-backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/mongodb:/data/db
    networks:
      - workshop1-backend
    restart: always

networks:
  workshop1-backend:
    driver: bridge
